package cron

import (
	"strings"
	"testing"

	"github.com/ezgamehost/ezdbbackup/internal/config"
)

func TestRenderProducesDeterministicSystemCronFile(t *testing.T) {
	t.Parallel()

	cfg := &config.Config{Jobs: map[string]config.JobConfig{
		"zeta": {
			Enabled:  true,
			Schedule: "30 4 * * 1-5",
			RunAs:    "backup",
		},
		"disabled": {
			Enabled:  false,
			Schedule: "not a schedule",
			RunAs:    "ignored",
		},
		"alpha": {
			Enabled:  true,
			Schedule: "0 2 * * *",
			RunAs:    "root",
		},
	}}

	got, err := Render(cfg, "/opt/ez'dbbackup", "/etc/ezdbbackup/config's.yml")
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	want := "# Generated by ezdbbackup. DO NOT EDIT.\n" +
		"# ezdbbackup-managed: v1\n" +
		"SHELL=/bin/sh\n" +
		"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n" +
		"\n" +
		"0 2 * * * root '/opt/ez'\"'\"'dbbackup' backup 'alpha' --config '/etc/ezdbbackup/config'\"'\"'s.yml'\n" +
		"30 4 * * 1-5 backup '/opt/ez'\"'\"'dbbackup' backup 'zeta' --config '/etc/ezdbbackup/config'\"'\"'s.yml'\n"
	if string(got) != want {
		t.Fatalf("Render() =\n%s\nwant:\n%s", got, want)
	}
	if strings.Contains(strings.ToLower(string(got)), "logrotate") {
		t.Fatalf("Render() unexpectedly contains logrotate content:\n%s", got)
	}
	if len(got) == 0 || got[len(got)-1] != '\n' {
		t.Fatalf("Render() does not end in a newline: %q", got)
	}
}

func TestRenderRejectsUnsafeInputs(t *testing.T) {
	t.Parallel()

	validConfig := func() *config.Config {
		return &config.Config{Jobs: map[string]config.JobConfig{
			"production": {
				Enabled:  true,
				Schedule: "0 2 * * *",
				RunAs:    "root",
			},
		}}
	}

	tests := []struct {
		name       string
		cfg        func() *config.Config
		binaryPath string
		configPath string
	}{
		{name: "nil config", cfg: func() *config.Config { return nil }, binaryPath: "/bin/ezdbbackup", configPath: "/etc/ezdbbackup.yml"},
		{name: "relative binary", cfg: validConfig, binaryPath: "bin/ezdbbackup", configPath: "/etc/ezdbbackup.yml"},
		{name: "relative config", cfg: validConfig, binaryPath: "/bin/ezdbbackup", configPath: "etc/ezdbbackup.yml"},
		{name: "binary newline", cfg: validConfig, binaryPath: "/bin/ezdbbackup\nevil", configPath: "/etc/ezdbbackup.yml"},
		{name: "binary percent", cfg: validConfig, binaryPath: "/opt/ez%dbbackup", configPath: "/etc/ezdbbackup.yml"},
		{name: "config carriage return", cfg: validConfig, binaryPath: "/bin/ezdbbackup", configPath: "/etc/ezdbbackup.yml\revil"},
		{name: "config nul", cfg: validConfig, binaryPath: "/bin/ezdbbackup", configPath: "/etc/ezdbbackup.yml\x00evil"},
		{name: "config percent", cfg: validConfig, binaryPath: "/bin/ezdbbackup", configPath: "/etc/ez%dbbackup.yml"},
		{name: "cron nickname", cfg: mutateRenderConfig(validConfig, func(cfg *config.Config) { setRenderJob(cfg, "production", "@daily", "root") }), binaryPath: "/bin/ezdbbackup", configPath: "/etc/ezdbbackup.yml"},
		{name: "six field schedule", cfg: mutateRenderConfig(validConfig, func(cfg *config.Config) { setRenderJob(cfg, "production", "0 0 2 * * *", "root") }), binaryPath: "/bin/ezdbbackup", configPath: "/etc/ezdbbackup.yml"},
		{name: "invalid schedule value", cfg: mutateRenderConfig(validConfig, func(cfg *config.Config) { setRenderJob(cfg, "production", "61 2 * * *", "root") }), binaryPath: "/bin/ezdbbackup", configPath: "/etc/ezdbbackup.yml"},
		{name: "question mark", cfg: mutateRenderConfig(validConfig, func(cfg *config.Config) { setRenderJob(cfg, "production", "0 2 ? * *", "root") }), binaryPath: "/bin/ezdbbackup", configPath: "/etc/ezdbbackup.yml"},
		{name: "day of week eight", cfg: mutateRenderConfig(validConfig, func(cfg *config.Config) { setRenderJob(cfg, "production", "0 2 * * 8", "root") }), binaryPath: "/bin/ezdbbackup", configPath: "/etc/ezdbbackup.yml"},
		{name: "schedule newline", cfg: mutateRenderConfig(validConfig, func(cfg *config.Config) { setRenderJob(cfg, "production", "0 2 * *\n*", "root") }), binaryPath: "/bin/ezdbbackup", configPath: "/etc/ezdbbackup.yml"},
		{name: "run user whitespace", cfg: mutateRenderConfig(validConfig, func(cfg *config.Config) { setRenderJob(cfg, "production", "0 2 * * *", "root admin") }), binaryPath: "/bin/ezdbbackup", configPath: "/etc/ezdbbackup.yml"},
		{name: "run user newline", cfg: mutateRenderConfig(validConfig, func(cfg *config.Config) { setRenderJob(cfg, "production", "0 2 * * *", "root\nevil") }), binaryPath: "/bin/ezdbbackup", configPath: "/etc/ezdbbackup.yml"},
		{name: "job name nul", cfg: func() *config.Config {
			return &config.Config{Jobs: map[string]config.JobConfig{
				"production\x00evil": {Enabled: true, Schedule: "0 2 * * *", RunAs: "root"},
			}}
		}, binaryPath: "/bin/ezdbbackup", configPath: "/etc/ezdbbackup.yml"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			if _, err := Render(tt.cfg(), tt.binaryPath, tt.configPath); err == nil {
				t.Fatal("Render() error = nil, want non-nil")
			}
		})
	}
}

// This fails if rendering rejects valid /etc/cron.d Sunday/list/range/step
// forms even though configuration validation accepts them.
func TestRenderAcceptsCronDDialect(t *testing.T) {
	t.Parallel()
	for _, schedule := range []string{
		"0 2 * * 7",
		"*/15 0-23/2 1,15 * 1-5",
		"*/15,7 0-23/2 1,15 * 1-5",
		"0,15,30,45 0-23/2 1-31/3 JAN,MAR,DEC SUN,MON-FRI",
	} {
		t.Run(schedule, func(t *testing.T) {
			t.Parallel()
			cfg := &config.Config{Jobs: map[string]config.JobConfig{
				"production": {Enabled: true, Schedule: schedule, RunAs: "root"},
			}}
			got, err := Render(cfg, "/bin/ezdbbackup", "/etc/ezdbbackup.yml")
			if err != nil {
				t.Fatalf("Render() error = %v, want /etc/cron.d schedule accepted", err)
			}
			if !strings.Contains(string(got), schedule+" root ") {
				t.Fatalf("Render() = %q, want unchanged schedule", got)
			}
		})
	}
}

func mutateRenderConfig(base func() *config.Config, mutate func(*config.Config)) func() *config.Config {
	return func() *config.Config {
		cfg := base()
		mutate(cfg)
		return cfg
	}
}

func setRenderJob(cfg *config.Config, name, schedule, runAs string) {
	cfg.Jobs[name] = config.JobConfig{Enabled: true, Schedule: schedule, RunAs: runAs}
}
