// Package cron renders and manages ezdbbackup system cron schedules.
package cron

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/ezgamehost/ezdbbackup/internal/config"
	robfigcron "github.com/robfig/cron/v3"
)

const (
	OwnershipMarker = "# ezdbbackup-managed: v1"
	systemPath      = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
)

var fiveFieldParser = robfigcron.NewParser(
	robfigcron.Minute | robfigcron.Hour | robfigcron.Dom | robfigcron.Month | robfigcron.Dow,
)

// Render returns a deterministic /etc/cron.d file for the enabled jobs in cfg.
func Render(cfg *config.Config, binaryPath, configPath string) ([]byte, error) {
	if cfg == nil {
		return nil, fmt.Errorf("render cron: configuration is required")
	}
	if err := validateRenderedPath("binary", binaryPath); err != nil {
		return nil, err
	}
	if err := validateRenderedPath("config", configPath); err != nil {
		return nil, err
	}

	var rendered bytes.Buffer
	fmt.Fprintln(&rendered, "# Generated by ezdbbackup. DO NOT EDIT.")
	fmt.Fprintln(&rendered, OwnershipMarker)
	fmt.Fprintln(&rendered, "SHELL=/bin/sh")
	fmt.Fprintf(&rendered, "PATH=%s\n\n", systemPath)

	for _, name := range cfg.EnabledJobNames() {
		job := cfg.Jobs[name]
		if err := rejectLineBreakOrNUL("job name", name); err != nil {
			return nil, err
		}
		if err := rejectLineBreakOrNUL("schedule for job "+name, job.Schedule); err != nil {
			return nil, err
		}
		fields := strings.Fields(job.Schedule)
		if len(fields) != 5 {
			return nil, fmt.Errorf("render cron: schedule for job %q must be a five-field cron expression", name)
		}
		if _, err := fiveFieldParser.Parse(job.Schedule); err != nil {
			return nil, fmt.Errorf("render cron: invalid schedule for job %q: %w", name, err)
		}
		if err := validateRunAs(name, job.RunAs); err != nil {
			return nil, err
		}

		fmt.Fprintf(
			&rendered,
			"%s %s %s backup %s --config %s\n",
			strings.Join(fields, " "),
			job.RunAs,
			posixQuote(binaryPath),
			posixQuote(name),
			posixQuote(configPath),
		)
	}

	return rendered.Bytes(), nil
}

func validateRenderedPath(name, value string) error {
	if err := rejectLineBreakOrNUL(name+" path", value); err != nil {
		return err
	}
	if !filepath.IsAbs(value) {
		return fmt.Errorf("render cron: %s path must be absolute", name)
	}
	return nil
}

func validateRunAs(jobName, runAs string) error {
	if err := rejectLineBreakOrNUL("run user for job "+jobName, runAs); err != nil {
		return err
	}
	if runAs == "" || strings.IndexFunc(runAs, unicode.IsSpace) >= 0 {
		return fmt.Errorf("render cron: run user for job %q must be a single non-empty field", jobName)
	}
	return nil
}

func rejectLineBreakOrNUL(name, value string) error {
	if strings.ContainsAny(value, "\r\n\x00") {
		return fmt.Errorf("render cron: %s contains a newline or NUL", name)
	}
	return nil
}

func posixQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}
